stages:
  - test
  - build

test:
  stage: test
  image: enriquerodbe/sbt-play:1.1.2_2.6.13
  cache:
    paths:
      - "sbt-cache/sbtboot"
      - "sbt-cache/boot"
      - "sbt-cache/ivy/cache"
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: amplify_api_test
    POSTGRES_USER: amplify
    POSTGRES_PASSWORD: amplify
    DB_HOST: postgres
    SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  script:
    - sbt coverageOn test it:test coverageReport

image: docker:stable
services:
  - docker:dind

build_latest:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --build-arg version=latest -t registry.gitlab.com/amplifyuy/amplify-api:latest .
    - docker push registry.gitlab.com/amplifyuy/amplify-api:latest
  only:
    - master

build_tag:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --build-arg version=$CI_COMMIT_TAG -t registry.gitlab.com/amplifyuy/amplify-api:$CI_COMMIT_TAG .
    - docker push registry.gitlab.com/amplifyuy/amplify-api:$CI_COMMIT_TAG
  only:
    - tags
