stages:
  - test
  - build

test:
  stage: test
  image: enriquerodbe/sbt-play:1.1.2_2.6.13
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: amplify_api_test
    POSTGRES_USER: amplify
    POSTGRES_PASSWORD: amplify
    DB_HOST: postgres
  script:
    - sbt coverageOn test
    - sbt coverageOn it:test
    - sbt coverageReport

build_latest:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --build-arg version=latest -t registry.gitlab.com/amplifyuy/amplify-api:latest .
    - docker push registry.gitlab.com/amplifyuy/amplify-api:latest
  only:
    - master

build_tag:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --build-arg version=$CI_COMMIT_TAG -t registry.gitlab.com/amplifyuy/amplify-api:$CI_COMMIT_TAG .
    - docker push registry.gitlab.com/amplifyuy/amplify-api:$CI_COMMIT_TAG
  only:
    - tags
