image: enriquerodbe/sbt-play:1.1.2_2.6.13

pipelines:
  branches:
    master:
      - step:
          caches:
            - sbt
          script:
            - sbt test
            - sbt it:test
            - sbt coverageReport
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker build --build-arg version=latest -t amplifyuy/amplify-api:latest .
            - docker push amplifyuy/amplify-api:latest
          services:
            - postgres
  tags:
    '*':
      - step:
          caches:
            - sbt
          script:
            - sbt test
            - sbt it:test
            - sbt coverageReport
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker build --build-arg version=$BITBUCKET_TAG -t amplifyuy/amplify-api:$BITBUCKET_TAG .
            - docker push amplifyuy/amplify-api:$BITBUCKET_TAG
          services:
            - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'amplify_api_test'
        POSTGRES_USER: 'amplify'
        POSTGRES_PASSWORD: 'amplify'

options:
  docker: true
