image: enriquerodbe/sbt-play:1.1.2_2.6.13

pipelines:
  default:
    - step:
        script:
          - sbt test
          - sbt it:test
          - sbt coverageReport
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker build --build-arg version=$BITBUCKET_BUILD_NUMBER -t amplifyuy/amplify-api:$BITBUCKET_BUILD_NUMBER .
          - docker push amplifyuy/amplify-api:$BITBUCKET_BUILD_NUMBER
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'amplify_api_test'
        POSTGRES_USER: 'amplify'
        POSTGRES_PASSWORD: 'amplify'

options:
  docker: true
