version: '2'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.0.5
    ports:
      - "8082:8080"
    environment:
      - API_URL=http://localhost:9000/assets/swagger.json
    depends_on:
      - app
  app:
    image: registry.gitlab.com/amplifyuy/amplify-api:latest
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=amplify-api-db
      - APPLICATION_SECRET=secret
      - SPOTIFY_CLIENT_ID=496a0e414ad74f94a75ee1c1610cbbf8
      - SPOTIFY_CLIENT_SECRET=e4fbe822cc554afa9d59473c835206e2
      - SPOTIFY_REDIRECT_URI=https://example.com/callback
      - CORS_ALLOWED_ORIGINS_0=http://localhost:8081 # Admin
      - CORS_ALLOWED_ORIGINS_1=http://localhost:8082 # Swagger
      - CORS_ALLOWED_HEADERS_0=Origin
      - CORS_ALLOWED_HEADERS_1=Content-Type
      - CORS_ALLOWED_HEADERS_2=X-Auth-Token
      - CORS_ALLOWED_HEADERS_3=Authorization
    depends_on:
      - amplify-api-db
  amplify-api-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=amplify
      - POSTGRES_USER=amplify
      - POSTGRES_DB=amplify_api_dev
